version: 2
linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/docs/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast" (`golangci-lint help linters --json | jq '[ .[] | select(.fast==true) ] | map(.name)'`).
  # Default: standard
  default: none
  # Enable specific linter.
  enable:
    - govet
  settings:
    # See the dedicated "linters.settings" documentation section.
    govet:
      disable-all: false 
      enable-all: true
      enable:
       - assign
        # Check for useless assignments.
       - fieldalignment
        # Check for common mistakes involving boolean operators.
       - bools
        #  This is the best  :) golangci-lint run --enable-only govet --fix